# Generated by Django 5.1.3 on 2024-12-27 05:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "photo_realtor",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Photo"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, verbose_name="Email Address"),
                ),
                (
                    "is_mvp",
                    models.BooleanField(default=False, verbose_name="MVP Realtor"),
                ),
                (
                    "hire_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Hire Date",
                    ),
                ),
            ],
        ),
    ]
