# Generated by Django 5.1.3 on 2024-12-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtor",
            options={
                "ordering": ["-hire_date"],
                "verbose_name": "Realtor",
                "verbose_name_plural": "Realtors",
            },
        ),
    ]
