# Generated by Django 5.1.3 on 2024-12-27 05:43

#This Django migration creates a Contact model with the following fields:
#- id: A unique identifier for the contact.
#- listing: The name of the listing the contact is associated with.
#- listing_id: The ID of the listing the contact is associated with.
#- name: The name of the contact.
#- email: The email address of the contact.
#- phone: The phone number of the contact.
#- message: An optional message from the contact.
#- contact_date: The date and time the contact was made.
#- user_id: The ID of the user associated with the contact (optional).


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing", models.CharField(max_length=200)),
                ("listing_id", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "contact_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("user_id", models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
