#This comment indicates that the Django migration file `0002_alter_contact_user_id.py` was generated by Django 5.1.3 on 2024-12-27 06:24. This migration file is part of the `contact` application and alters the `user_id` field of the `Contact` model.
# Generated by Django 5.1.3 on 2024-12-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user_id",
            field=models.IntegerField(blank=True),
        ),
    ]


#contact\migrations\0003_alter_contact_user_id.py
# Generated by Django 5.1.3 on 2024-12-27 06:25
from django.db import migrations, models

