# Generated by Django 5.1.3 on 2024-12-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
