# Generated by Django 5.1.3 on 2024-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contact_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="realtor_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
